config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations/registrations'
  }
  namespace :contacts do
    root to: 'contacts#index'
    resources :contacts, only: [:update]
    resources :people
    resources :organizations
  end

  namespace :admin do
    resources :users, only: %i[index new create] do
      put :suspend
    end
  end

  namespace :api do
    resources :tasks, only: %i[index create destroy update]
  end

  resources :circles, only: [:new, :edit, :update, :create]
  resources :cases
  resources :people
  resources :organizations

  root to: 'cases#index'
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :circle_contacts
  has_many :circles, through: :circle_contacts

  has_many :cases
  belongs_to :account
  belongs_to :contactable, polymorphic: true

  scope :people, -> { where(contactable_type: 'Person') }
  scope :organizations, -> { where(contactable_type: 'Organization') }

  validates_associated :contactable

  def name
    contactable.name
  end
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :organization, required: false
  has_one :contact, as: :contactable
  has_many :cases, through: :contact

  validates :first_name, :last_name, presence: true

  def name
    [first_name, last_name].join(' ')
  end
end

app/controllers/contacts/contacts_controller.rb
class Contacts::ContactsController < ApplicationController
  def index
    @search = search_params
    @contacts = ContactSearch.new(
      search_params
    ).results
  end

  def update
    circles_form = ContactCirclesForm.new(contact_params)

    if circles_form.save
      flash[:notice] = 'Circles have been successfully updated.'
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = 'There was a problem with updating circles.'
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def contact_params
    params.require(:contact).permit(circle_ids: []).merge(
      contact_id: params[:id]
    )
  end

  def search_params
    (params[:contact_search] || {}).merge(
      account_id: current_account.id
    )
  end
end

app/controllers/contacts/organizations_controller.rb
class Contacts::OrganizationsController < ApplicationController
  def index
    @search = search_params
    @organizations = OrganizationSearch.new(
      search_params
    ).results
  end

  def show
    @organization = Organization.find(params[:id])
    @people = @organization.people
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def update
    @organization = Organization.find(params[:id])

    if @organization.update(organization_params)
      flash[:notice] = 'Organization has been successfully updated.'
      redirect_to contacts_organizations_path
    else
      render :edit
    end
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)

    contact = current_account.contacts.build(contactable: @organization)

    if contact.save
      flash[:notice] = 'Organization has been successfully created.'
      redirect_to contacts_organizations_path
    else
      render :new
    end
  end

  private

  def organization_params
    params.require(:organization).permit(:name).to_h
  end

  def search_params
    (params[:organization_search] || {}).merge(account_id: current_account.id)
  end
end

app/controllers/contacts/people_controller.rb
class Contacts::PeopleController < ApplicationController
  def index
    @search = search_params
    @people = PersonSearch.new(
      search_params
    ).results
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if @person.update(person_params)
      flash[:notice] = 'Contact has been successfully updated.'
      redirect_to contacts_people_path
    else
      render :edit
    end
  end

  def create
    @person = Person.new(person_params)

    contact = current_account.contacts.build(contactable: @person)

    if contact.save
      flash[:notice] = 'Contact has been successfully created.'
      redirect_to contacts_people_path
    else
      render :new
    end
  end

  private

  def person_params
    params.require(:person).permit(:first_name, :last_name, :title, :job_title, :organization_id)
  end

  def search_params
    (params[:person_search] || {}).merge(account_id: current_account.id)
  end
end

app/views/contacts/people/_form.html.erb
<div class="col-lg-8">
  <%= form_for [:contacts, @person], html: { class: "card" } do |f| %>
  <div class="card-body">
    <h3 class="card-title">Edit Profile</h3>
    <div class="row">
      <div class="col-sm-6 col-md-2">
        <div class="form-group">
          <label class="form-label">Title</label>
          <%= f.collection_select :title, %w(Mr Mrs Miss Ms Sir Dr Lady Lord), :to_s, :to_s, {}, {include_blank: true, class: 'form-control custom-select'} %>
        </div>
      </div>
      <div class="col-sm-6 col-md-5">
        <div class="form-group">
          <label class="form-label">First Name</label>
          <%= f.text_field :first_name, class: 'form-control', placeholder: 'First name' %>
        </div>
      </div>
      <div class="col-sm-6 col-md-5">
        <div class="form-group">
          <label class="form-label">Last Name</label>
          <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last name' %>
        </div>
      </div>
      <div class="col-sm-6 col-md-6">
        <div class="form-group">
          <label class="form-label">Job Title</label>
          <%= f.text_field :job_title, class: 'form-control', placeholder: 'Lead Accounting Associate' %>
        </div>
      </div>
      <div class="col-sm-6 col-md-6">
        <%= render 'forms/organization_select', f: f %>
      </div>
    </div>
    <div class="card-footer text-right">
      <%= f.submit "Update profile", class: 'btn btn-primary' %>
    </div>
  </div>
  <% end %>
</div>

app/views/contacts/people/index.html.erb
<div class="container">
  <div class="page-header">
    <h1 class="page-title">
      People
    </h1>
  </div>

  <div class="row row-cards">
    <div class="col-lg-3 order-lg-1 mb-4">
      <%= link_to new_contacts_person_path, class: "btn btn-block btn-primary mb-6" do %>
        Add new
      <% end %>
      <div class="card">
        <%= form_for :person_search, method: :get do |f| %>
          <div class="card-header">
            <h3 class="card-title">Filter results</h3>
          </div>
          <div class="card-body">
            <fieldset>
              <div class="form-group">
                <label class="form-label">Name</label>
                <%= f.text_field :name, value: @search[:name], class: "form-control" %>
              </div>
              <%= render 'forms/organization_select', f: f %>

              <div class="form-group">
                <%= f.label :with_cases, class: 'custom-switch' do %>
                  <%= f.check_box :with_cases, class: 'custom-switch-input', checked: @search[:with_cases] == '1' %>
                  <span class="custom-switch-indicator"></span>
                  <span class="custom-switch-description">With open cases</span>
                <% end %>
              </div>

            </fieldset>
          </div>
          <div class="card-footer text-right">
            <div class="d-flex">
              <a href="javascript:void(0)" class="btn btn-link">Cancel</a>
              <%= f.submit 'Submit', class: "btn btn-primary ml-auto" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-9">
      <div class="card">
        <div class="table-responsive">
          <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
            <thead>
              <tr>
                <th class="text-center w-1"><i class="icon-people"></i></th>
                <th>User</th>
                <th>Organization</th>
                <th>Activity</th>
                <th class="text-right"><i class="icon-settings"></i></th>
              </tr>
            </thead>
            <tbody>
              <% @people.each do |person| %>
                <tr>
                  <td class="text-center">
                    <div class="avatar d-block" style="background-image: url(<%= Faker::Avatar.image %>)"/>
                  </td>
                  <td>
                    <div>
                      <%= link_to "#{person.first_name} #{person.last_name}", contacts_person_path(person) %>
                    </div>
                    <div class="small text-muted">
                      <%= person.job_title %>
                    </div>
                  </td>
                  <td>
                    <% if person.organization %>
                      <%= link_to person.organization.name, contacts_organization_path(person.organization) %>
                    <% end %>
                  </td>
                  <td>
                    <div class="small text-muted">Registered</div>
                    <div><%= pretty_date(person.created_at) %></div>
                  </td>
                  <td class="text-right">
                    <%= link_to 'Manage', edit_contacts_person_path(person), class: "btn btn-secondary btn-sm" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/people/show.html.erb
<div class="container">
  <div class="page-header">
    <h1 class="page-title">
      Person
    </h1>
  </div>

  <div class="row row-cards row-deck">
    <div class="col-md-6 col-lg-4">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title"></h3>
          <div class="card-options">
            <%= link_to "Edit", edit_contacts_person_path(@person), class: "btn btn-primary btn-sm" %>
          </div>
        </div>
        <div class="card-body">
          <div class="media">
            <span class="avatar avatar-xxl mr-5" style="background-image: url(<%= Faker::Avatar.image %>)"></span>
            <div class="media-body">
              <h4 class="m-0"><%= @person.title %> <%= @person.first_name %> <%= @person.last_name %></h4>
              <p class="text-muted mb-0">
                <%= @person.job_title %>
                <% if @person.organization %>
                  @ <%= link_to @person.organization.name, contacts_organization_path(@person.organization) %>
                <% end %>
              </p>
              <ul class="social-links list-inline mb-0 mt-2">
                <li class="list-inline-item">
                  <a href="javascript:void(0)" title="" data-toggle="tooltip" data-original-title="Facebook"><i class="fa fa-facebook"></i></a>
                </li>
                <li class="list-inline-item">
                  <a href="javascript:void(0)" title="" data-toggle="tooltip" data-original-title="Twitter"><i class="fa fa-twitter"></i></a>
                </li>
                <li class="list-inline-item">
                  <a href="javascript:void(0)" title="" data-toggle="tooltip" data-original-title="1234567890"><i class="fa fa-phone"></i></a>
                </li>
                <li class="list-inline-item">
                  <a href="javascript:void(0)" title="" data-toggle="tooltip" data-original-title="@skypename"><i class="fa fa-skype"></i></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="card">
        <%= render 'forms/circle_form', contact: @person.contact %>
      </div>
    </div>
    <div class="col-lg-8">
      <div class="card">
        <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
              <a class="nav-link active">Cases</a>
            </li>
          </ul>
        </div>
        <%= render 'cases/cases', cases: @person.cases %>
      </div>
    </div>
  </div>
</div>