config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations/registrations'
  }
  namespace :contacts do
    root to: 'contacts#index'
    resources :contacts, only: [:update]
    resources :people
    resources :organizations
  end

  namespace :admin do
    resources :users, only: %i[index new create] do
      put :suspend
    end
  end

  namespace :api do
    resources :tasks, only: %i[index create destroy update]
  end

  resources :circles, only: [:new, :edit, :update, :create]
  resources :cases
  resources :people
  resources :organizations

  root to: 'cases#index'
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :circle_contacts
  has_many :circles, through: :circle_contacts

  has_many :cases
  belongs_to :account
  belongs_to :contactable, polymorphic: true

  scope :people, -> { where(contactable_type: 'Person') }
  scope :organizations, -> { where(contactable_type: 'Organization') }

  validates_associated :contactable

  def name
    contactable.name
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :people
  has_one :contact, as: :contactable
  has_many :cases, through: :contact

  validates :name, presence: true
end

app/controllers/contacts/contacts_controller.rb
class Contacts::ContactsController < ApplicationController
  def index
    @search = search_params
    @contacts = ContactSearch.new(
      search_params
    ).results
  end

  def update
    circles_form = ContactCirclesForm.new(contact_params)

    if circles_form.save
      flash[:notice] = 'Circles have been successfully updated.'
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = 'There was a problem with updating circles.'
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def contact_params
    params.require(:contact).permit(circle_ids: []).merge(
      contact_id: params[:id]
    )
  end

  def search_params
    (params[:contact_search] || {}).merge(
      account_id: current_account.id
    )
  end
end

app/controllers/contacts/organizations_controller.rb
class Contacts::OrganizationsController < ApplicationController
  def index
    @search = search_params
    @organizations = OrganizationSearch.new(
      search_params
    ).results
  end

  def show
    @organization = Organization.find(params[:id])
    @people = @organization.people
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def update
    @organization = Organization.find(params[:id])

    if @organization.update(organization_params)
      flash[:notice] = 'Organization has been successfully updated.'
      redirect_to contacts_organizations_path
    else
      render :edit
    end
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)

    contact = current_account.contacts.build(contactable: @organization)

    if contact.save
      flash[:notice] = 'Organization has been successfully created.'
      redirect_to contacts_organizations_path
    else
      render :new
    end
  end

  private

  def organization_params
    params.require(:organization).permit(:name).to_h
  end

  def search_params
    (params[:organization_search] || {}).merge(account_id: current_account.id)
  end
end

app/controllers/contacts/people_controller.rb
class Contacts::PeopleController < ApplicationController
  def index
    @search = search_params
    @people = PersonSearch.new(
      search_params
    ).results
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if @person.update(person_params)
      flash[:notice] = 'Contact has been successfully updated.'
      redirect_to contacts_people_path
    else
      render :edit
    end
  end

  def create
    @person = Person.new(person_params)

    contact = current_account.contacts.build(contactable: @person)

    if contact.save
      flash[:notice] = 'Contact has been successfully created.'
      redirect_to contacts_people_path
    else
      render :new
    end
  end

  private

  def person_params
    params.require(:person).permit(:first_name, :last_name, :title, :job_title, :organization_id)
  end

  def search_params
    (params[:person_search] || {}).merge(account_id: current_account.id)
  end
end

app/views/contacts/organizations/_form.html.erb
<div class="col-lg-8">
  <%= form_for [:contacts, @organization], html: { class: "card" } do |f| %>
  <div class="card-body">
    <h3 class="card-title">Edit Organization</h3>
    <div class="row">
      <div class="col-sm-12 col-md-12">
        <div class="form-group">
          <label class="form-label">Name</label>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Organization name' %>
        </div>
      </div>
    </div>
    <div class="card-footer text-right">
      <%= f.submit "Save organization", class: 'btn btn-primary' %>
    </div>
  </div>
  <% end %>
</div>

app/views/contacts/organizations/index.html.erb
<div class="container">
  <div class="page-header">
    <h1 class="page-title">
      Organizations
    </h1>
  </div>

  <div class="row row-cards">
    <div class="col-lg-3 order-lg-1 mb-4">
      <%= link_to new_contacts_organization_path, class: "btn btn-block btn-primary mb-6" do %>
        Add new
      <% end %>
      <div class="card">
        <%= form_for :organization_search, method: :get do |f| %>
          <div class="card-header">
            <h3 class="card-title">Filter results</h3>
          </div>
          <div class="card-body">
            <fieldset>
              <div class="form-group">
                <label class="form-label">Company name<span class="form-required">*</span></label>
                <%= f.text_field :name, value: @search[:name], class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :with_cases, class: 'custom-switch' do %>
                  <%= f.check_box :with_cases, class: 'custom-switch-input', checked: @search[:with_cases] == '1' %>
                  <span class="custom-switch-indicator"></span>
                  <span class="custom-switch-description">With open cases</span>
                <% end %>
              </div>
            </fieldset>
          </div>
          <div class="card-footer text-right">
            <div class="d-flex">
              <a href="javascript:void(0)" class="btn btn-link">Cancel</a>
              <%= f.submit 'Submit', class: "btn btn-primary ml-auto" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-lg-9">
      <div class="card">
        <div class="table-responsive">
          <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
            <thead>
              <tr>
                <th class="text-center w-1"><i class="icon-people"></i></th>
                <th>Organization</th>
                <th>Contacts</th>
                <th>Activity</th>
                <th class="text-right"><i class="icon-settings"></i></th>
              </tr>
            </thead>
            <tbody>
              <% @organizations.each do |organization| %>
                <tr>
                  <td class="text-center">
                    <div class="avatar d-block" style="background-image: url(<%= Faker::Avatar.image %>)"/>
                  </td>
                  <td>
                    <div>
                      <%= link_to organization.name, contacts_organization_path(organization) %>
                    </div>
                    <div class="small text-muted">
                      Tax number: 133 555 111
                    </div>
                  </td>
                  <td>
                    <%= organization.people.count %>
                  </td>
                  <td>
                    <div class="small text-muted">Registered</div>
                    <div><%= pretty_date(organization.created_at) %></div>
                  </td>
                  <td class="text-right">
                    <%= link_to 'Manage', edit_contacts_organization_path(organization), class: "btn btn-secondary btn-sm" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/organizations/show.html.erb
<div class="container">
  <div class="page-header">
    <h1 class="page-title">
      Organization
    </h1>
  </div>

  <div class="row row-cards row-deck">
    <div class="col-md-6 col-lg-4">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title"><%= @organization.name %></h3>
          <div class="card-options">
            <%= link_to "Edit", edit_contacts_organization_path(@organization), class: "btn btn-primary btn-sm" %>
          </div>
        </div>
        <div class="card-body">
        </div>
      </div>

      <div class="card">
        <%= render 'forms/circle_form', contact: @organization.contact %>
      </div>

      <div class="card">
        <div class="card-header">
          <h3 class="card-title">People at <%= @organization.name %></h3>
        </div>
        <div class="card-body o-auto" style="height: 15rem">
          <ul class="list-unstyled list-separated">
            <% @people.each do |person| %>
            <li class="list-separated-item">
              <div class="row align-items-center">
                <div class="col-auto">
                  <span class="avatar avatar-md d-block" style="background-image: url(<%= Faker::Avatar.image %>)"></span>
                </div>
                <div class="col">
                  <div>
                    <%= link_to "#{person.first_name} #{person.last_name}", contacts_person_path(person) %>
                  </div>
                  <small class="d-block item-except text-sm text-muted h-1x"><%= person.job_title %></small>
                </div>
              </div>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-lg-8">
      <div class="card">
        <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
              <a class="nav-link active">Cases</a>
            </li>
          </ul>
        </div>
        <%= render 'cases/cases', cases: @organization.cases %>
      </div>
    </div>
  </div>
</div>