config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations/registrations'
  }
  namespace :contacts do
    root to: 'contacts#index'
    resources :contacts, only: [:update]
    resources :people
    resources :organizations
  end

  namespace :admin do
    resources :users, only: %i[index new create] do
      put :suspend
    end
  end

  namespace :api do
    resources :tasks, only: %i[index create destroy update]
  end

  resources :circles, only: [:new, :edit, :update, :create]
  resources :cases
  resources :people
  resources :organizations

  root to: 'cases#index'
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :circles
  has_many :users
  has_many :contacts
  has_many :organizations, through: :contacts, source: 'contactable', source_type: 'Organization'
  has_many :people, through: :contacts, source: 'contactable', source_type: 'Person'

  validates :name, presence: true, uniqueness: true
end

app/views/forms/_circle_form.html.erb
<%= form_for [:contacts, contact] do |f| %>
  <div class="card-header">
    <h3 class="card-title">Circles</h3>
  </div>
  <div class="card-body">
    <div class="form-group">
      <div class="selectgroup selectgroup-pills">
        <%= f.collection_check_boxes(:circle_ids, current_account.circles, :id, :title) do |f_circle| %>
          <%= f_circle.label(class: 'selectgroup-item') do %>
            <%= f_circle.check_box(class: 'selectgroup-input') %>
            <span class="selectgroup-button"><%= f_circle.text %></span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-footer text-right">
    <%= f.submit "Save changes", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/forms/_circle_select.html.erb
<div class="form-group">
  <label class="form-label">Circle</label>
  <%= f.collection_select :circle_id, current_account.circles, :id, :title, { include_blank: "Select a circle", selected: selected }, { class: 'form-control custom-select'} %>
</div>

app/views/forms/_contact_select.html.erb
<div class="form-group">
  <label class="form-label">Contact</label>
  <%= f.collection_select :contact_id, current_account.contacts, :id, :name, { include_blank: "Select a contact" }, { class: 'form-control custom-select'} %>
</div>

app/views/forms/_organization_select.html.erb
<div class="form-group">
  <label class="form-label">Organization</label>
  <%= f.collection_select :organization_id, current_account.organizations, :id, :name, { include_blank: "Select a company" }, { class: 'form-control custom-select'} %>
</div>

app/views/forms/_user_select.html.erb
<div class="form-group">
  <label class="form-label">Assigned</label>
  <%= f.collection_select :assigned_user_id, current_account.users, :id, :email, { include_blank: "Select a user" }, { class: 'form-control custom-select'} %>
</div>