config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations/registrations'
  }
  namespace :contacts do
    root to: 'contacts#index'
    resources :contacts, only: [:update]
    resources :people
    resources :organizations
  end

  namespace :admin do
    resources :users, only: %i[index new create] do
      put :suspend
    end
  end

  namespace :api do
    resources :tasks, only: %i[index create destroy update]
  end

  resources :circles, only: [:new, :edit, :update, :create]
  resources :cases
  resources :people
  resources :organizations

  root to: 'cases#index'
end

app/models/user.rb
class User < ApplicationRecord
  devise :confirmable, :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable, :registerable, :invitable, validate_on_invite: true

  belongs_to :account
  has_many :tasks

  def suspend!
    return true if suspended_at
    update(suspended_at: Time.current)
  end

  def active_for_authentication?
    super && !suspended_at
  end

  def inactive_message
    !suspended_at ? super : :suspended_account
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseController
    before_action :load_users, only: %i[index suspend]

    def index; end

    def new
      @invitation_form = AccountInvitationForm.new
    end

    def create
      @invitation_form = AccountInvitationForm.new(invitation_form_params)

      if @invitation_form.save
        flash[:notice] = 'Successfully invited new user!'
        redirect_to admin_users_path
      else
        flash[:alert] = @invitation_form.errors.full_messages.to_sentence
        render :new
      end
    end

    def suspend
      @user = @users.find(params[:user_id])

      if @user.suspend!
        flash[:notice] = 'Successfully suspened this user!'
      else
        flash[:alert] = 'There was a problem with suspending this user.'
      end

      redirect_to admin_users_path
    end

    private

    def invitation_form_params
      params.require(:account_invitation_form).permit(
        :email
      ).merge(user_id: current_user.id)
    end

    def load_users
      @users ||= UserSearch.new(account_id: current_user.account_id).results
    end
  end
end

app/views/admin/users/_form.html.erb
<%= form_for(@invitation_form, url: admin_users_path, html: { class: 'card'} ) do |f| %>
  <div class="card-body p-6">

    <div class="form-group">
      <%= f.label :email, class: 'form-label' %>
      <%= f.email_field :email, placeholder: 'Enter email', autocomplete: "email", class: 'form-control' %>
    </div>

    <div class="form-footer">
      <%= f.submit "Invite", class: "btn btn-primary btn-block", data: { disable: true } %>
    </div>
  </div>
<% end %>

app/views/admin/users/_user_table.html.erb
<table class="table card-table">
  <thead>
    <tr>
      <th class="text-center w-1"><i class="far fa-user"></i></th>
      <th>Name</th>
      <th>Joined at</th>
      <th>Confirmed at</th>
      <th>Role</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="<%= 'suspended' if user.suspended_at %>">
        <td class="text-center">
          <%= render 'shared/avatar' %>
        </td>
        <td><%= user.email %></td>
        <td><%= pretty_date(user.created_at) %></td>
        <td><%= pretty_date(user.confirmed_at) %></td>
        <td><%= user.admin? ? 'Admin' : 'User' %></td>
        <td class="text-right">
          <%= button_to 'Suspend', admin_user_suspend_path(user), method: :put, class: 'btn btn-secondary btn-sm', disabled: user.suspended_at, data: { confirm: 'This operation is irreversible. Do you wish to continue?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="page-header">
    <h1 class="page-title">
      Account users
    </h1>
  </div>
  <div class="row">
    <div class="col-lg-3 order-lg-1 mb-4">
      <%= link_to new_admin_user_path, class: 'btn btn-block btn-primary mb-6' do %>
        Add new
      <% end %>
      <%= render 'admin/sidebar' %>
    </div>
    <div class="col-lg-9">
      <div class="card">
        <%= render 'user_table' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="container">
  <div class="page-header">
    <h1 class="page-title">
      New user
    </h1>
  </div>
  <div class="row">
    <div class="col-lg-3 order-lg-1 mb-4">
      <%= render 'admin/sidebar' %>
    </div>
    <div class="col-lg-9">
      <%= render 'form' %>
    </div>
  </div>
</div>